//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP_Project2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VP_Project2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _104_3a54bcbb5cf4a3d332bb8fa01e984580 {
            get {
                object obj = ResourceManager.GetObject("104-3a54bcbb5cf4a3d332bb8fa01e984580", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1325_4964b3c064941df4cd4ca33d6273755b {
            get {
                object obj = ResourceManager.GetObject("1325-4964b3c064941df4cd4ca33d6273755b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1330_c9e3c2c69b56b5cb0e5185284d65fbcc {
            get {
                object obj = ResourceManager.GetObject("1330-c9e3c2c69b56b5cb0e5185284d65fbcc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1886_ada4ef40cc95171acb93a9604e9a53ac {
            get {
                object obj = ResourceManager.GetObject("1886-ada4ef40cc95171acb93a9604e9a53ac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1891_13fba827e786720473efdd744e72870a {
            get {
                object obj = ResourceManager.GetObject("1891-13fba827e786720473efdd744e72870a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2156_b31f49a1955f020817991a39cb2abc0a {
            get {
                object obj = ResourceManager.GetObject("2156-b31f49a1955f020817991a39cb2abc0a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2175_c73f2daeeeeda02d037799184aa578ad {
            get {
                object obj = ResourceManager.GetObject("2175-c73f2daeeeeda02d037799184aa578ad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2249_410de2b82213d5354b97a0d630212600 {
            get {
                object obj = ResourceManager.GetObject("2249-410de2b82213d5354b97a0d630212600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2252_369fdb9b25f7c27ead252a2bab2525e3 {
            get {
                object obj = ResourceManager.GetObject("2252-369fdb9b25f7c27ead252a2bab2525e3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2253_33c3bd09286ead7de261225c8f5a3012 {
            get {
                object obj = ResourceManager.GetObject("2253-33c3bd09286ead7de261225c8f5a3012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _262x262_932083c8e817ab4940a48caa184812d6 {
            get {
                object obj = ResourceManager.GetObject("262x262-932083c8e817ab4940a48caa184812d6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _262x262_d5d1c4c3c4cf07a3ed39916f98f4c1e2__1_ {
            get {
                object obj = ResourceManager.GetObject("262x262-d5d1c4c3c4cf07a3ed39916f98f4c1e2 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2821_91ccdb306b2074a48781c7419f8bcd29 {
            get {
                object obj = ResourceManager.GetObject("2821-91ccdb306b2074a48781c7419f8bcd29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _331_e29b5cb10cbddd994bb1e848efb2eba1 {
            get {
                object obj = ResourceManager.GetObject("331-e29b5cb10cbddd994bb1e848efb2eba1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap account_269_866236 {
            get {
                object obj = ResourceManager.GetObject("account-269-866236", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apples_262x262_85f72fae0670bc8d329a85a6f6c169f6 {
            get {
                object obj = ResourceManager.GetObject("apples-262x262-85f72fae0670bc8d329a85a6f6c169f6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apricots_400g_262x262_6277ba3faa710f1f85afbc6663113be3 {
            get {
                object obj = ResourceManager.GetObject("apricots-400g-262x262-6277ba3faa710f1f85afbc6663113be3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_food_fruits_vegetables_collection_fruit_vegetable_portrait_format_healthy_eating_diet_apples_oranges_tomatoes_190446153 {
            get {
                object obj = ResourceManager.GetObject("background-food-fruits-vegetables-collection-fruit-vegetable-portrait-format-heal" +
                        "thy-eating-diet-apples-oranges-tomatoes-190446153", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cherries_262x262_4d82a790017e38609f9f226b0791414a {
            get {
                object obj = ResourceManager.GetObject("cherries-262x262-4d82a790017e38609f9f226b0791414a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_girl_signapore_online_grocers_organic {
            get {
                object obj = ResourceManager.GetObject("green-girl-signapore-online-grocers-organic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logged_out_home_hero {
            get {
                object obj = ResourceManager.GetObject("logged-out-home-hero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Riverford_Logo_blackt {
            get {
                object obj = ResourceManager.GetObject("Riverford_Logo_blackt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap riverford_organic_farmers_office {
            get {
                object obj = ResourceManager.GetObject("riverford-organic-farmers-office", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap salad_bag_1500x1000_c9d5ff2e6f3020cb076a446df29268a4 {
            get {
                object obj = ResourceManager.GetObject("salad-bag-1500x1000-c9d5ff2e6f3020cb076a446df29268a4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tomatoes_262x262_05e49e6885688ff74235aaa1fd9a744d {
            get {
                object obj = ResourceManager.GetObject("tomatoes-262x262-05e49e6885688ff74235aaa1fd9a744d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
